# Generated by Django 2.0.5 on 2018-08-04 21:32

import basic_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20180804_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=basic_app.models.UserProfileInfo.get_upload_path),
        ),
    ]
